controller_manager:
  ros__parameters:
    update_rate: 100

    franka_joint_controller:
      type: position_controllers/JointGroupPositionController

    franka_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    franka_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


franka_joint_trajectory_controller:
  ros__parameters:
    joints:
      - Base_Joint
      - Shoulder_Roll
      - Shoulder_Yaw
      - Elbow_Pitch
      - Wrist_Pitch
      - Wrist_Yaw
      - Wrist_Roll
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

franka_joint_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort