controller_manager:
  ros__parameters:
    update_rate: 100

    canadarm_joint_controller:
      type: effort_controllers/JointGroupEffortController

    canadarm_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster



canadarm_joint_controller:
  ros__parameters:
    joints:
      - Base_Joint
      - Shoulder_Roll
      - Shoulder_Yaw
      - Elbow_Pitch
      - Wrist_Pitch
      - Wrist_Yaw
      - Wrist_Roll
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort