controller_manager:
  ros__parameters:
    update_rate: 100

    ets_vii_joint_controller:
      type: effort_controllers/JointGroupPositionController

    ets_vii_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ets_vii_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


ets_vii_joint_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      joint1:
        p: 5000.0
        i: 0.0
        d: 10.0
      joint2:
        p: 500.0
        i: 0.0
        d: 500.0
      joint3:
        p: 2000.0
        i: 0.0
        d: 500.0
      joint4:
        p: 3000.0
        i: 0.0
        d: 300.0
      joint5:
        p: 300.0
        i: 0.0
        d: 100.0
      joint6:
        p: 5.0
        i: 0.0
        d: 10.0


ets_vii_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
